[package]
name = "hello_world_01" # proqramin adi
version = "0.1.0" # proqramin versiyasi
edition = "2024" # programin yazildigi Rust versiyasi

[dependencies] # asagida proqramin istifade edeceyi kutuphaneler ve frameworklar qeyd olunur:
empty = "0.0.4" # bos kutuphane, hec bir funksiyasi yoxdur